### ISSUE TITLE
Feature/User-list

### ISSUE THREAD

**Issue by lowejay** [thynameisjayvee/espresso#66]
## Expected Output
- Show all registered users in small cards
- Add search filters for student or teacher
## Todo
- [x] Create userlist page
- [x] Add cards for each user
- [ ] Add search / filters
